# Generated by Django 4.0 on 2022-01-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_city_emailaccount_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='account_type',
            field=models.CharField(choices=[('member', 'member'), ('clinic', 'clinic')], default='member', max_length=255, verbose_name='type'),
        ),
    ]
