# Generated by Django 4.0 on 2022-01-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_emailaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone'),
        ),
    ]
