# Generated by Django 4.0 on 2022-01-02 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_emailaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([\\s\\d]+)$', 'Only digits characters')], verbose_name='phone'),
        ),
    ]
