# Generated by Django 4.0 on 2022-02-16 19:53

import config.utils.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromClinic', to='account.emailaccount')),
            ],
            options={
                'verbose_name': 'المقالة',
                'verbose_name_plural': 'المقالات',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clinic_name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('facebook', models.URLField(blank=True, max_length=500, null=True, verbose_name='facebook')),
                ('instagram', models.URLField(blank=True, max_length=500, null=True, verbose_name='instagram')),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinicss', to='account.emailaccount')),
            ],
            options={
                'verbose_name': 'العيادة',
                'verbose_name_plural': 'العيادات',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'الرسالة',
                'verbose_name_plural': 'الرسائل',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True, verbose_name='gender')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memberss', to='account.emailaccount')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الاعضاء',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True, verbose_name='gender')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='image')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='family')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='weight')),
                ('adopt_date', models.DateField(blank=True, null=True, verbose_name='birth')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('chip_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='chip_number')),
                ('clinic', models.ManyToManyField(blank=True, null=True, related_name='pet_clinic', to='vety.Clinic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner', to='vety.member')),
            ],
            options={
                'verbose_name': 'حيوان اليف',
                'verbose_name_plural': 'حيوانات الاليفة',
            },
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'نوع الحيوان',
                'verbose_name_plural': 'انواع الحيوانات',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('next', models.DateField(blank=True, null=True, verbose_name='next')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_vaccine', to='vety.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petss_vaccine', to='vety.pet')),
            ],
            options={
                'verbose_name': 'اللقاح',
                'verbose_name_plural': 'اللقاحات',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('allergy', models.CharField(max_length=255, verbose_name='allergy')),
                ('description', models.TextField(verbose_name='description')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicss_report', to='vety.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petss_report', to='vety.pet')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
            },
        ),
        migrations.CreateModel(
            name='RateClinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('point', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='point')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicss_clinic_rating', to='vety.clinic')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberss_clinic_rating', to='vety.member')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'تقييمات',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_type', to='vety.pettype'),
        ),
        migrations.CreateModel(
            name='LikeBlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_like', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogss_rating_like', to='vety.blog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberss_rating_like', to='vety.member')),
            ],
            options={
                'verbose_name': 'اعجاب المقالة',
                'verbose_name_plural': 'اعجاب المقالة',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^([\\s\\d]+)$', 'Only digits characters')], verbose_name='phone_number')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vety.clinic')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الاطباء',
            },
        ),
        migrations.CreateModel(
            name='DislikeBlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_dislike', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogss_rating_dislike', to='vety.blog')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberss_rating_dislike', to='vety.member')),
            ],
            options={
                'verbose_name': 'كره المقالة',
                'verbose_name_plural': 'كره المقالة',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromPet', to='vety.pettype'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', config.utils.models.CustomDateTimeField()),
                ('end_date', config.utils.models.CustomDateTimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicss_appointment', to='vety.clinic')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberss_appointment', to='vety.member')),
            ],
            options={
                'verbose_name': 'الموعد',
                'verbose_name_plural': 'المواعيد',
            },
        ),
    ]
