# Generated by Django 4.0 on 2022-01-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_emailaccount_account_type'),
        ('vety', '0002_delete_city_alter_clinic_user_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='created',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.emailaccount'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.emailaccount'),
        ),
    ]
