# Generated by Django 4.0 on 2022-01-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_emailaccount_phone_number'),
        ('vety', '0005_clinic_id_member_id_alter_clinic_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinicss', to='account.emailaccount'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memberss', to='account.emailaccount'),
        ),
    ]
